/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.cloud.ai.dataagent.workflow.node;

import static com.alibaba.cloud.ai.dataagent.constant.Constant.PLAN_CURRENT_STEP;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.IS_ONLY_NL2SQL;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_EXECUTE_NODE_OUTPUT;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_GENERATE_COUNT;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_GENERATE_OUTPUT;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_REGENERATE_REASON;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_RESULT_LIST_MEMORY;

import com.alibaba.cloud.ai.dataagent.bo.DbConfigBO;
import com.alibaba.cloud.ai.dataagent.bo.schema.DisplayStyleBO;
import com.alibaba.cloud.ai.dataagent.bo.schema.ResultBO;
import com.alibaba.cloud.ai.dataagent.bo.schema.ResultSetBO;
import com.alibaba.cloud.ai.dataagent.connector.DbQueryParameter;
import com.alibaba.cloud.ai.dataagent.connector.accessor.Accessor;
import com.alibaba.cloud.ai.dataagent.constant.Constant;
import com.alibaba.cloud.ai.dataagent.dto.datasource.SqlRetryDto;
import com.alibaba.cloud.ai.dataagent.dto.planner.ExecutionStep;
import com.alibaba.cloud.ai.dataagent.enums.TextType;
import com.alibaba.cloud.ai.dataagent.prompt.PromptHelper;
import com.alibaba.cloud.ai.dataagent.properties.DataAgentProperties;
import com.alibaba.cloud.ai.dataagent.service.llm.LlmService;
import com.alibaba.cloud.ai.dataagent.service.nl2sql.Nl2SqlService;
import com.alibaba.cloud.ai.dataagent.util.ChatResponseUtil;
import com.alibaba.cloud.ai.dataagent.util.DatabaseUtil;
import com.alibaba.cloud.ai.dataagent.util.FluxUtil;
import com.alibaba.cloud.ai.dataagent.util.JsonUtil;
import com.alibaba.cloud.ai.dataagent.util.PlanProcessUtil;
import com.alibaba.cloud.ai.dataagent.util.StateUtil;
import com.alibaba.cloud.ai.graph.GraphResponse;
import com.alibaba.cloud.ai.graph.OverAllState;
import com.alibaba.cloud.ai.graph.action.NodeAction;
import com.alibaba.cloud.ai.graph.streaming.StreamingOutput;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

/**
 * SQL execution node that executes SQL queries against the database.
 *
 * <p>
 * This node is responsible for: - Executing SQL queries generated by previous nodes -
 * Handling query results and errors - Providing streaming feedback to users during
 * execution - Managing step-by-step result accumulation
 *
 * @author zhangshenghang
 */
@Slf4j
@Component
@AllArgsConstructor
public class SqlExecuteNode implements NodeAction {

	private final DatabaseUtil databaseUtil;

	private final Nl2SqlService nl2SqlService;

	private final LlmService llmService;

	private final DataAgentProperties properties;

	private static final int SAMPLE_DATA_NUMBER = 20;

	private static final BeanOutputConverter<DisplayStyleBO> DISPLAY_STYLE_CONVERTER = new BeanOutputConverter<>(
			DisplayStyleBO.class);

	@Override
	public Map<String, Object> apply(OverAllState state) throws Exception {

		Integer currentStep = PlanProcessUtil.getCurrentStepNumber(state);

		String sqlQuery = StateUtil.getStringValue(state, SQL_GENERATE_OUTPUT);
		sqlQuery = nl2SqlService.sqlTrim(sqlQuery);

		log.info("Executing SQL query: {}", sqlQuery);

		// Get the agent ID from the state
		String agentIdStr = StateUtil.getStringValue(state, Constant.AGENT_ID);
		if (StringUtils.isBlank(agentIdStr)) {
			throw new IllegalStateException("Agent ID cannot be empty.");
		}

		Long agentId = Long.valueOf(agentIdStr);

		// Dynamically get the data source configuration for an agent
		DbConfigBO dbConfig = databaseUtil.getAgentDbConfig(agentId);

		return executeSqlQuery(state, currentStep, sqlQuery, dbConfig, agentId);
	}

	/**
	 * Executes the SQL query against the database and handles the results.
	 *
	 * <p>
	 * This method follows the business-logic-first pattern: 1. Execute the actual SQL
	 * query immediately 2. Process and store the results 3. Create streaming output for
	 * user experience only
	 * @param state The overall state containing execution context
	 * @param currentStep The current step number in the execution plan
	 * @param sqlQuery The SQL query to execute
	 * @param dbConfig The database configuration to use for execution
	 * @param agentId The agent ID
	 * @return Map containing the generator for streaming output
	 */
	@SuppressWarnings("unchecked")
	private Map<String, Object> executeSqlQuery(OverAllState state, Integer currentStep, String sqlQuery,
			DbConfigBO dbConfig, Long agentId) {
		// Execute business logic first - actual SQL execution
		DbQueryParameter dbQueryParameter = new DbQueryParameter();
		dbQueryParameter.setSql(sqlQuery);
		dbQueryParameter.setSchema(dbConfig.getSchema());

		Accessor dbAccessor = databaseUtil.getAgentAccessor(agentId);
		final Map<String, Object> result = new HashMap<>();

		Flux<ChatResponse> startFlux = Flux.just(ChatResponseUtil.createResponse("开始执行SQL..."),
				ChatResponseUtil.createResponse("执行SQL查询："),
				ChatResponseUtil.createPureResponse(TextType.SQL.getStartSign()),
				ChatResponseUtil.createResponse(sqlQuery),
				ChatResponseUtil.createPureResponse(TextType.SQL.getEndSign()));

		Mono<ExecutedSqlResult> sqlExecution = Mono
			.fromCallable(() -> executeAndStoreResult(state, currentStep, sqlQuery, dbConfig, dbQueryParameter,
					dbAccessor, result))
			.subscribeOn(Schedulers.boundedElastic());

		Flux<ChatResponse> executionFlux = sqlExecution
			.flatMapMany(executed -> Flux.concat(baseResultResponses(executed.resultSet()),
					chartUpdateResponses(state, executed.resultSet())))
			.onErrorResume(e -> {
				String errorMessage = e.getMessage();
				log.error("SQL execution failed - SQL as follows: \n {} \n ", sqlQuery, e);
				result.put(SQL_REGENERATE_REASON, SqlRetryDto.sqlExecute(errorMessage));
				return Flux.just(ChatResponseUtil.createResponse("SQL执行失败: " + errorMessage));
			});

		Flux<ChatResponse> displayFlux = Flux.concat(startFlux, executionFlux);

		// Create generator using utility class, returning pre-computed business logic
		// result
		Flux<GraphResponse<StreamingOutput>> generator = FluxUtil.createStreamingGeneratorWithMessages(this.getClass(),
				state, v -> result, displayFlux);
		return Map.of(SQL_EXECUTE_NODE_OUTPUT, generator);
	}

	/**
	 * 调用大模型获取图表配置信息并填充到ResultSetBO中
	 * @param state 整体状态
	 * @param resultSetBO SQL执行结果
	 */
	private ExecutedSqlResult executeAndStoreResult(OverAllState state, Integer currentStep, String sqlQuery,
			DbConfigBO dbConfig, DbQueryParameter dbQueryParameter, Accessor dbAccessor, Map<String, Object> result)
			throws Exception {
		ResultSetBO resultSetBO = dbAccessor.executeSqlAndReturnObject(dbConfig, dbQueryParameter);
		String strResultSetJson = JsonUtil.getObjectMapper().writeValueAsString(resultSetBO);

		result.put(SQL_REGENERATE_REASON, SqlRetryDto.empty());
		result.put(SQL_RESULT_LIST_MEMORY, resultSetBO.getData());
		result.put(PLAN_CURRENT_STEP, currentStep + 1);
		result.put(SQL_GENERATE_COUNT, 0);

		try {
			Map<String, String> existingResults = StateUtil.getObjectValue(state, SQL_EXECUTE_NODE_OUTPUT, Map.class,
					new HashMap<>());
			Map<String, String> updatedResults = PlanProcessUtil.addStepResult(existingResults, currentStep,
					strResultSetJson);
			result.put(SQL_EXECUTE_NODE_OUTPUT, updatedResults);

			ExecutionStep.ToolParameters currentStepParams = PlanProcessUtil.getCurrentExecutionStep(state)
				.getToolParameters();
			currentStepParams.setSqlQuery(sqlQuery);
		}
		catch (Exception stateEx) {
			log.warn("State processing after successful SQL execution failed (non-critical): {}", stateEx.getMessage());
		}

		log.info("SQL execution successful, result count: {}",
				resultSetBO.getData() != null ? resultSetBO.getData().size() : 0);
		return new ExecutedSqlResult(resultSetBO);
	}

	private Flux<ChatResponse> baseResultResponses(ResultSetBO resultSetBO) {
		return resultPayloadResponses(resultSetBO, tableDisplayStyle())
			.startWith(ChatResponseUtil.createResponse("执行SQL完成"), ChatResponseUtil.createResponse("SQL查询结果："));
	}

	private Flux<ChatResponse> chartUpdateResponses(OverAllState state, ResultSetBO resultSetBO) {
		return enrichResultSetWithChartConfig(state, resultSetBO)
			.flatMapMany(displayStyle -> resultPayloadResponses(resultSetBO, displayStyle))
			.onErrorResume(e -> {
				log.warn("Failed to publish optional chart config, keeping table result: {}", e.getMessage());
				return Flux.empty();
			});
	}

	private Flux<ChatResponse> resultPayloadResponses(ResultSetBO resultSetBO, DisplayStyleBO displayStyle) {
		return Mono
			.fromCallable(() -> JsonUtil.getObjectMapper()
				.writeValueAsString(ResultBO.builder().resultSet(resultSetBO).displayStyle(displayStyle).build()))
			.flatMapMany(
					strResultJson -> Flux.just(ChatResponseUtil.createPureResponse(TextType.RESULT_SET.getStartSign()),
							ChatResponseUtil.createPureResponse(strResultJson),
							ChatResponseUtil.createPureResponse(TextType.RESULT_SET.getEndSign())));
	}

	private Mono<DisplayStyleBO> enrichResultSetWithChartConfig(OverAllState state, ResultSetBO resultSetBO) {
		if (state.value(IS_ONLY_NL2SQL, false)) {
			log.debug("NL2SQL-only mode skips optional chart generation and uses table display");
			return Mono.empty();
		}
		if (!this.properties.isEnableSqlResultChart()) {
			log.debug("Sql result chart is disabled, set display style as table default");
			return Mono.empty();
		}

		return Mono.defer(() -> {
			try {
				// 获取用户查询
				String userQuery = StateUtil.getCanonicalQuery(state);

				// 将SQL结果转换为JSON字符串，限制数据量以避免提示词过长
				String sqlResultJson = JsonUtil.getObjectMapper()
					.writeValueAsString(resultSetBO.getData() != null
							? resultSetBO.getData().stream().limit(SAMPLE_DATA_NUMBER).toList() : null);

				// 构建用户提示词，包含SQL结果数据
				String userPrompt = String.format("""
						# 正式任务

						<最新>用户输入: %s
						范例数据: %s

						# 输出
						""", userQuery != null ? userQuery : "数据可视化", sqlResultJson);

				// 加载data-view-analyze提示词模板（系统提示词）
				String fullPrompt = PromptHelper.buildDataViewAnalysisPrompt();
				// 分割系统提示词和用户提示词模板
				String[] parts = fullPrompt.split("=== 用户输入 ===", 2);
				// 渲染系统提示词（当前没有变量，直接使用模板内容）
				String systemPrompt = parts[0].trim();

				log.debug("Built chart config generation system prompt as follows \n {} \n", systemPrompt);
				log.debug("Built chart config generation user prompt as follows \n {} \n", userPrompt);

				// 调用LLM生成图表配置（使用系统提示词和用户提示词）
				return llmService.toStringFlux(llmService.call(systemPrompt, userPrompt, DisplayStyleBO.class))
					.collect(StringBuilder::new, StringBuilder::append)
					.map(StringBuilder::toString)
					.filter(StringUtils::isNotBlank)
					.map(DISPLAY_STYLE_CONVERTER::convert)
					.timeout(Duration.ofMillis(properties.getEnrichSqlResultTimeout()))
					.doOnNext(displayStyle -> {
						log.debug("Successfully enriched ResultSetBO with chart config: type={}, title={}, x={}, y={}",
								displayStyle.getType(), displayStyle.getTitle(), displayStyle.getX(),
								displayStyle.getY());
					});
			}
			catch (Exception e) {
				return Mono.error(e);
			}
		}).onErrorResume(e -> {
			log.warn("Failed to generate optional chart config, keeping table result: {}", e.getMessage());
			return Mono.empty();
		});
	}

	private DisplayStyleBO tableDisplayStyle() {
		DisplayStyleBO displayStyle = new DisplayStyleBO();
		displayStyle.setType("table");
		return displayStyle;
	}

	private record ExecutedSqlResult(ResultSetBO resultSet) {
	}

}
